# Generated by Django 5.1.2 on 2024-10-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='FileUpload',
        ),
    ]
